//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:11:04 PM CET 
//


package cezeszamlazo.hu.gov.nav.schemas._2013.szamla;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for asvanyolaj_tipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="asvanyolaj_tipus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="homerseklet" type="{http://schemas.nav.gov.hu/2013/szamla}decimal_tipus" minOccurs="0"/>
 *         &lt;element name="tomeg" type="{http://schemas.nav.gov.hu/2013/szamla}decimal_tipus" minOccurs="0"/>
 *         &lt;element name="tomeg_mert" type="{http://schemas.nav.gov.hu/2013/szamla}string_tipus" minOccurs="0"/>
 *         &lt;element name="suruseg" type="{http://schemas.nav.gov.hu/2013/szamla}decimal_tipus" minOccurs="0"/>
 *         &lt;element name="suruseg_mert" type="{http://schemas.nav.gov.hu/2013/szamla}string_tipus" minOccurs="0"/>
 *         &lt;element name="terfogat" type="{http://schemas.nav.gov.hu/2013/szamla}decimal_tipus" minOccurs="0"/>
 *         &lt;element name="terfogat_mert" type="{http://schemas.nav.gov.hu/2013/szamla}string_tipus" minOccurs="0"/>
 *         &lt;element name="minoseg" type="{http://schemas.nav.gov.hu/2013/szamla}string_tipus" minOccurs="0"/>
 *         &lt;element name="tanusitas" type="{http://schemas.nav.gov.hu/2013/szamla}string_tipus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "asvanyolaj_tipus", propOrder = {
    "homerseklet",
    "tomeg",
    "tomegMert",
    "suruseg",
    "surusegMert",
    "terfogat",
    "terfogatMert",
    "minoseg",
    "tanusitas"
})
public class AsvanyolajTipus {

    protected BigDecimal homerseklet;
    protected BigDecimal tomeg;
    @XmlElement(name = "tomeg_mert")
    protected String tomegMert;
    protected BigDecimal suruseg;
    @XmlElement(name = "suruseg_mert")
    protected String surusegMert;
    protected BigDecimal terfogat;
    @XmlElement(name = "terfogat_mert")
    protected String terfogatMert;
    protected String minoseg;
    protected String tanusitas;

    /**
     * Gets the value of the homerseklet property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHomerseklet() {
        return homerseklet;
    }

    /**
     * Sets the value of the homerseklet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHomerseklet(BigDecimal value) {
        this.homerseklet = value;
    }

    /**
     * Gets the value of the tomeg property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTomeg() {
        return tomeg;
    }

    /**
     * Sets the value of the tomeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTomeg(BigDecimal value) {
        this.tomeg = value;
    }

    /**
     * Gets the value of the tomegMert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomegMert() {
        return tomegMert;
    }

    /**
     * Sets the value of the tomegMert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomegMert(String value) {
        this.tomegMert = value;
    }

    /**
     * Gets the value of the suruseg property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSuruseg() {
        return suruseg;
    }

    /**
     * Sets the value of the suruseg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSuruseg(BigDecimal value) {
        this.suruseg = value;
    }

    /**
     * Gets the value of the surusegMert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurusegMert() {
        return surusegMert;
    }

    /**
     * Sets the value of the surusegMert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurusegMert(String value) {
        this.surusegMert = value;
    }

    /**
     * Gets the value of the terfogat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTerfogat() {
        return terfogat;
    }

    /**
     * Sets the value of the terfogat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTerfogat(BigDecimal value) {
        this.terfogat = value;
    }

    /**
     * Gets the value of the terfogatMert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerfogatMert() {
        return terfogatMert;
    }

    /**
     * Sets the value of the terfogatMert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerfogatMert(String value) {
        this.terfogatMert = value;
    }

    /**
     * Gets the value of the minoseg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinoseg() {
        return minoseg;
    }

    /**
     * Sets the value of the minoseg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinoseg(String value) {
        this.minoseg = value;
    }

    /**
     * Gets the value of the tanusitas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTanusitas() {
        return tanusitas;
    }

    /**
     * Sets the value of the tanusitas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTanusitas(String value) {
        this.tanusitas = value;
    }

}
