//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:11:04 PM CET 
//


package cezeszamlazo.hu.gov.nav.schemas._2013.szamla;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for csomszer_forg_hoz_tipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="csomszer_forg_hoz_tipus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="termek_dij" type="{http://schemas.nav.gov.hu/2013/szamla}decimal_tipus"/>
 *         &lt;element name="reszenkent_forg_hoz" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="vevo_nyilatkozat" type="{http://schemas.nav.gov.hu/2013/szamla}vevo_nyilatkozat_tipus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "csomszer_forg_hoz_tipus", propOrder = {
    "termekDij",
    "reszenkentForgHoz",
    "vevoNyilatkozat"
})
public class CsomszerForgHozTipus {

    @XmlElement(name = "termek_dij", required = true)
    protected BigDecimal termekDij;
    @XmlElement(name = "reszenkent_forg_hoz")
    protected boolean reszenkentForgHoz;
    @XmlElement(name = "vevo_nyilatkozat")
    protected VevoNyilatkozatTipus vevoNyilatkozat;

    /**
     * Gets the value of the termekDij property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTermekDij() {
        return termekDij;
    }

    /**
     * Sets the value of the termekDij property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTermekDij(BigDecimal value) {
        this.termekDij = value;
    }

    /**
     * Gets the value of the reszenkentForgHoz property.
     * 
     */
    public boolean isReszenkentForgHoz() {
        return reszenkentForgHoz;
    }

    /**
     * Sets the value of the reszenkentForgHoz property.
     * 
     */
    public void setReszenkentForgHoz(boolean value) {
        this.reszenkentForgHoz = value;
    }

    /**
     * Gets the value of the vevoNyilatkozat property.
     * 
     * @return
     *     possible object is
     *     {@link VevoNyilatkozatTipus }
     *     
     */
    public VevoNyilatkozatTipus getVevoNyilatkozat() {
        return vevoNyilatkozat;
    }

    /**
     * Sets the value of the vevoNyilatkozat property.
     * 
     * @param value
     *     allowed object is
     *     {@link VevoNyilatkozatTipus }
     *     
     */
    public void setVevoNyilatkozat(VevoNyilatkozatTipus value) {
        this.vevoNyilatkozat = value;
    }

}
