//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:11:04 PM CET 
//


package cezeszamlazo.hu.gov.nav.schemas._2013.szamla;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for foldikozl_tipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="foldikozl_tipus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hengerur" type="{http://schemas.nav.gov.hu/2013/szamla}decimal_tipus" minOccurs="0"/>
 *         &lt;element name="teljesitmeny" type="{http://schemas.nav.gov.hu/2013/szamla}decimal_tipus" minOccurs="0"/>
 *         &lt;element name="forgba_datum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="futottkm" type="{http://schemas.nav.gov.hu/2013/szamla}decimal_tipus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "foldikozl_tipus", propOrder = {
    "hengerur",
    "teljesitmeny",
    "forgbaDatum",
    "futottkm"
})
public class FoldikozlTipus {

    protected BigDecimal hengerur;
    protected BigDecimal teljesitmeny;
    @XmlElement(name = "forgba_datum")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar forgbaDatum;
    protected BigDecimal futottkm;

    /**
     * Gets the value of the hengerur property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHengerur() {
        return hengerur;
    }

    /**
     * Sets the value of the hengerur property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHengerur(BigDecimal value) {
        this.hengerur = value;
    }

    /**
     * Gets the value of the teljesitmeny property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTeljesitmeny() {
        return teljesitmeny;
    }

    /**
     * Sets the value of the teljesitmeny property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTeljesitmeny(BigDecimal value) {
        this.teljesitmeny = value;
    }

    /**
     * Gets the value of the forgbaDatum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getForgbaDatum() {
        return forgbaDatum;
    }

    /**
     * Sets the value of the forgbaDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setForgbaDatum(XMLGregorianCalendar value) {
        this.forgbaDatum = value;
    }

    /**
     * Gets the value of the futottkm property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFutottkm() {
        return futottkm;
    }

    /**
     * Sets the value of the futottkm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFutottkm(BigDecimal value) {
        this.futottkm = value;
    }

}
