//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:11:04 PM CET 
//


package cezeszamlazo.hu.gov.nav.schemas._2013.szamla;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gazolaj_beszerz_tipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gazolaj_beszerz_tipus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rendszam">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="km_ora_allas" type="{http://schemas.nav.gov.hu/2013/szamla}decimal_tipus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gazolaj_beszerz_tipus", propOrder = {
    "rendszam",
    "kmOraAllas"
})
public class GazolajBeszerzTipus {

    @XmlElement(required = true)
    protected String rendszam;
    @XmlElement(name = "km_ora_allas", required = true)
    protected BigDecimal kmOraAllas;

    /**
     * Gets the value of the rendszam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRendszam() {
        return rendszam;
    }

    /**
     * Sets the value of the rendszam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRendszam(String value) {
        this.rendszam = value;
    }

    /**
     * Gets the value of the kmOraAllas property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKmOraAllas() {
        return kmOraAllas;
    }

    /**
     * Sets the value of the kmOraAllas property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKmOraAllas(BigDecimal value) {
        this.kmOraAllas = value;
    }

}
