//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:11:04 PM CET 
//


package cezeszamlazo.hu.gov.nav.schemas._2013.szamla;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for kepviselo_tipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="kepviselo_tipus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adoszam" type="{http://schemas.nav.gov.hu/2013/szamla}adoszam_tipus" minOccurs="0"/>
 *         &lt;element name="nev" type="{http://schemas.nav.gov.hu/2013/szamla}string_tipus"/>
 *         &lt;element name="cim" type="{http://schemas.nav.gov.hu/2013/szamla}cim_tipus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kepviselo_tipus", propOrder = {
    "adoszam",
    "nev",
    "cim"
})
public class KepviseloTipus {

    protected String adoszam;
    @XmlElement(required = true)
    protected String nev;
    @XmlElement(required = true)
    protected CimTipus cim;

    /**
     * Gets the value of the adoszam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdoszam() {
        return adoszam;
    }

    /**
     * Sets the value of the adoszam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdoszam(String value) {
        this.adoszam = value;
    }

    /**
     * Gets the value of the nev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNev() {
        return nev;
    }

    /**
     * Sets the value of the nev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNev(String value) {
        this.nev = value;
    }

    /**
     * Gets the value of the cim property.
     * 
     * @return
     *     possible object is
     *     {@link CimTipus }
     *     
     */
    public CimTipus getCim() {
        return cim;
    }

    /**
     * Sets the value of the cim property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimTipus }
     *     
     */
    public void setCim(CimTipus value) {
        this.cim = value;
    }

}
