//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:11:04 PM CET 
//


package cezeszamlazo.hu.gov.nav.schemas._2013.szamla;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for kozl_eszk_inf_tipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="kozl_eszk_inf_tipus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="foldikozl" type="{http://schemas.nav.gov.hu/2013/szamla}foldikozl_tipus" minOccurs="0"/>
 *         &lt;element name="legikozl" type="{http://schemas.nav.gov.hu/2013/szamla}legikozl_tipus" minOccurs="0"/>
 *         &lt;element name="vizikozl" type="{http://schemas.nav.gov.hu/2013/szamla}vizikozl_tipus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kozl_eszk_inf_tipus", propOrder = {
    "foldikozl",
    "legikozl",
    "vizikozl"
})
public class KozlEszkInfTipus {

    protected FoldikozlTipus foldikozl;
    protected LegikozlTipus legikozl;
    protected VizikozlTipus vizikozl;

    /**
     * Gets the value of the foldikozl property.
     * 
     * @return
     *     possible object is
     *     {@link FoldikozlTipus }
     *     
     */
    public FoldikozlTipus getFoldikozl() {
        return foldikozl;
    }

    /**
     * Sets the value of the foldikozl property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoldikozlTipus }
     *     
     */
    public void setFoldikozl(FoldikozlTipus value) {
        this.foldikozl = value;
    }

    /**
     * Gets the value of the legikozl property.
     * 
     * @return
     *     possible object is
     *     {@link LegikozlTipus }
     *     
     */
    public LegikozlTipus getLegikozl() {
        return legikozl;
    }

    /**
     * Sets the value of the legikozl property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegikozlTipus }
     *     
     */
    public void setLegikozl(LegikozlTipus value) {
        this.legikozl = value;
    }

    /**
     * Gets the value of the vizikozl property.
     * 
     * @return
     *     possible object is
     *     {@link VizikozlTipus }
     *     
     */
    public VizikozlTipus getVizikozl() {
        return vizikozl;
    }

    /**
     * Sets the value of the vizikozl property.
     * 
     * @param value
     *     allowed object is
     *     {@link VizikozlTipus }
     *     
     */
    public void setVizikozl(VizikozlTipus value) {
        this.vizikozl = value;
    }

}
