//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:11:04 PM CET 
//


package cezeszamlazo.hu.gov.nav.schemas._2013.szamla;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hu.gov.nav.schemas._2013.szamla package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Szamlak_QNAME = new QName("http://schemas.nav.gov.hu/2013/szamla", "szamlak");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hu.gov.nav.schemas._2013.szamla
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SzamlakTipus }
     * 
     */
    public SzamlakTipus createSzamlakTipus() {
        return new SzamlakTipus();
    }

    /**
     * Create an instance of {@link NemKotelezoTipus }
     * 
     */
    public NemKotelezoTipus createNemKotelezoTipus() {
        return new NemKotelezoTipus();
    }

    /**
     * Create an instance of {@link TermekSzolgaltatasTetelekTipus }
     * 
     */
    public TermekSzolgaltatasTetelekTipus createTermekSzolgaltatasTetelekTipus() {
        return new TermekSzolgaltatasTetelekTipus();
    }

    /**
     * Create an instance of {@link GyujtoSzlaTipus }
     * 
     */
    public GyujtoSzlaTipus createGyujtoSzlaTipus() {
        return new GyujtoSzlaTipus();
    }

    /**
     * Create an instance of {@link FejlecTipus }
     * 
     */
    public FejlecTipus createFejlecTipus() {
        return new FejlecTipus();
    }

    /**
     * Create an instance of {@link OsszesitesTipus }
     * 
     */
    public OsszesitesTipus createOsszesitesTipus() {
        return new OsszesitesTipus();
    }

    /**
     * Create an instance of {@link VevoTipus }
     * 
     */
    public VevoTipus createVevoTipus() {
        return new VevoTipus();
    }

    /**
     * Create an instance of {@link CimTipus }
     * 
     */
    public CimTipus createCimTipus() {
        return new CimTipus();
    }

    /**
     * Create an instance of {@link ModositoSzlaTipus }
     * 
     */
    public ModositoSzlaTipus createModositoSzlaTipus() {
        return new ModositoSzlaTipus();
    }

    /**
     * Create an instance of {@link CsomszerForgHozTipus }
     * 
     */
    public CsomszerForgHozTipus createCsomszerForgHozTipus() {
        return new CsomszerForgHozTipus();
    }

    /**
     * Create an instance of {@link FoldikozlTipus }
     * 
     */
    public FoldikozlTipus createFoldikozlTipus() {
        return new FoldikozlTipus();
    }

    /**
     * Create an instance of {@link AsvanyolajTipus }
     * 
     */
    public AsvanyolajTipus createAsvanyolajTipus() {
        return new AsvanyolajTipus();
    }

    /**
     * Create an instance of {@link VisszIgenyTipus }
     * 
     */
    public VisszIgenyTipus createVisszIgenyTipus() {
        return new VisszIgenyTipus();
    }

    /**
     * Create an instance of {@link VegosszegTipus }
     * 
     */
    public VegosszegTipus createVegosszegTipus() {
        return new VegosszegTipus();
    }

    /**
     * Create an instance of {@link VizikozlTipus }
     * 
     */
    public VizikozlTipus createVizikozlTipus() {
        return new VizikozlTipus();
    }

    /**
     * Create an instance of {@link JovEngKereskJovErtTipus }
     * 
     */
    public JovEngKereskJovErtTipus createJovEngKereskJovErtTipus() {
        return new JovEngKereskJovErtTipus();
    }

    /**
     * Create an instance of {@link KepviseloTipus }
     * 
     */
    public KepviseloTipus createKepviseloTipus() {
        return new KepviseloTipus();
    }

    /**
     * Create an instance of {@link LegikozlTipus }
     * 
     */
    public LegikozlTipus createLegikozlTipus() {
        return new LegikozlTipus();
    }

    /**
     * Create an instance of {@link SzamlakibocsatoTipus }
     * 
     */
    public SzamlakibocsatoTipus createSzamlakibocsatoTipus() {
        return new SzamlakibocsatoTipus();
    }

    /**
     * Create an instance of {@link BeszallokartyaTipus }
     * 
     */
    public BeszallokartyaTipus createBeszallokartyaTipus() {
        return new BeszallokartyaTipus();
    }

    /**
     * Create an instance of {@link SzamlaTipus }
     * 
     */
    public SzamlaTipus createSzamlaTipus() {
        return new SzamlaTipus();
    }

    /**
     * Create an instance of {@link ZaradekokTipus }
     * 
     */
    public ZaradekokTipus createZaradekokTipus() {
        return new ZaradekokTipus();
    }

    /**
     * Create an instance of {@link GazolajBeszerzTipus }
     * 
     */
    public GazolajBeszerzTipus createGazolajBeszerzTipus() {
        return new GazolajBeszerzTipus();
    }

    /**
     * Create an instance of {@link VevoNyilatkozatTipus }
     * 
     */
    public VevoNyilatkozatTipus createVevoNyilatkozatTipus() {
        return new VevoNyilatkozatTipus();
    }

    /**
     * Create an instance of {@link AfarovatTipus }
     * 
     */
    public AfarovatTipus createAfarovatTipus() {
        return new AfarovatTipus();
    }

    /**
     * Create an instance of {@link VisszIgenytetelTipus }
     * 
     */
    public VisszIgenytetelTipus createVisszIgenytetelTipus() {
        return new VisszIgenytetelTipus();
    }

    /**
     * Create an instance of {@link KozlEszkInfTipus }
     * 
     */
    public KozlEszkInfTipus createKozlEszkInfTipus() {
        return new KozlEszkInfTipus();
    }

    /**
     * Create an instance of {@link TermekdijSzerzesAtvallalasTipus }
     * 
     */
    public TermekdijSzerzesAtvallalasTipus createTermekdijSzerzesAtvallalasTipus() {
        return new TermekdijSzerzesAtvallalasTipus();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SzamlakTipus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.nav.gov.hu/2013/szamla", name = "szamlak")
    public JAXBElement<SzamlakTipus> createSzamlak(SzamlakTipus value) {
        return new JAXBElement<SzamlakTipus>(_Szamlak_QNAME, SzamlakTipus.class, null, value);
    }

}
