//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:11:04 PM CET 
//


package cezeszamlazo.hu.gov.nav.schemas._2013.szamla;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for szamla_tipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="szamla_tipus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fejlec" type="{http://schemas.nav.gov.hu/2013/szamla}fejlec_tipus"/>
 *         &lt;element name="szamlakibocsato" type="{http://schemas.nav.gov.hu/2013/szamla}szamlakibocsato_tipus"/>
 *         &lt;element name="vevo" type="{http://schemas.nav.gov.hu/2013/szamla}vevo_tipus"/>
 *         &lt;element name="kepviselo" type="{http://schemas.nav.gov.hu/2013/szamla}kepviselo_tipus" minOccurs="0"/>
 *         &lt;element name="termek_szolgaltatas_tetelek" type="{http://schemas.nav.gov.hu/2013/szamla}termek_szolgaltatas_tetelek_tipus" maxOccurs="unbounded"/>
 *         &lt;element name="modosito_szla" type="{http://schemas.nav.gov.hu/2013/szamla}modosito_szla_tipus" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="gyujto_szla" type="{http://schemas.nav.gov.hu/2013/szamla}gyujto_szla_tipus" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="zaradekok" type="{http://schemas.nav.gov.hu/2013/szamla}zaradekok_tipus" minOccurs="0"/>
 *         &lt;element name="nem_kotelezo" type="{http://schemas.nav.gov.hu/2013/szamla}nem_kotelezo_tipus" minOccurs="0"/>
 *         &lt;element name="osszesites" type="{http://schemas.nav.gov.hu/2013/szamla}osszesites_tipus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "szamla_tipus", propOrder = {
    "fejlec",
    "szamlakibocsato",
    "vevo",
    "kepviselo",
    "termekSzolgaltatasTetelek",
    "modositoSzla",
    "gyujtoSzla",
    "zaradekok",
    "nemKotelezo",
    "osszesites"
})
public class SzamlaTipus {

    @XmlElement(required = true)
    protected FejlecTipus fejlec;
    @XmlElement(required = true)
    protected SzamlakibocsatoTipus szamlakibocsato;
    @XmlElement(required = true)
    protected VevoTipus vevo;
    protected KepviseloTipus kepviselo;
    @XmlElement(name = "termek_szolgaltatas_tetelek", required = true)
    protected List<TermekSzolgaltatasTetelekTipus> termekSzolgaltatasTetelek;
    @XmlElement(name = "modosito_szla")
    protected List<ModositoSzlaTipus> modositoSzla;
    @XmlElement(name = "gyujto_szla")
    protected List<GyujtoSzlaTipus> gyujtoSzla;
    protected ZaradekokTipus zaradekok;
    @XmlElement(name = "nem_kotelezo")
    protected NemKotelezoTipus nemKotelezo;
    @XmlElement(required = true)
    protected OsszesitesTipus osszesites;

    /**
     * Gets the value of the fejlec property.
     * 
     * @return
     *     possible object is
     *     {@link FejlecTipus }
     *     
     */
    public FejlecTipus getFejlec() {
        return fejlec;
    }

    /**
     * Sets the value of the fejlec property.
     * 
     * @param value
     *     allowed object is
     *     {@link FejlecTipus }
     *     
     */
    public void setFejlec(FejlecTipus value) {
        this.fejlec = value;
    }

    /**
     * Gets the value of the szamlakibocsato property.
     * 
     * @return
     *     possible object is
     *     {@link SzamlakibocsatoTipus }
     *     
     */
    public SzamlakibocsatoTipus getSzamlakibocsato() {
        return szamlakibocsato;
    }

    /**
     * Sets the value of the szamlakibocsato property.
     * 
     * @param value
     *     allowed object is
     *     {@link SzamlakibocsatoTipus }
     *     
     */
    public void setSzamlakibocsato(SzamlakibocsatoTipus value) {
        this.szamlakibocsato = value;
    }

    /**
     * Gets the value of the vevo property.
     * 
     * @return
     *     possible object is
     *     {@link VevoTipus }
     *     
     */
    public VevoTipus getVevo() {
        return vevo;
    }

    /**
     * Sets the value of the vevo property.
     * 
     * @param value
     *     allowed object is
     *     {@link VevoTipus }
     *     
     */
    public void setVevo(VevoTipus value) {
        this.vevo = value;
    }

    /**
     * Gets the value of the kepviselo property.
     * 
     * @return
     *     possible object is
     *     {@link KepviseloTipus }
     *     
     */
    public KepviseloTipus getKepviselo() {
        return kepviselo;
    }

    /**
     * Sets the value of the kepviselo property.
     * 
     * @param value
     *     allowed object is
     *     {@link KepviseloTipus }
     *     
     */
    public void setKepviselo(KepviseloTipus value) {
        this.kepviselo = value;
    }

    /**
     * Gets the value of the termekSzolgaltatasTetelek property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the termekSzolgaltatasTetelek property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTermekSzolgaltatasTetelek().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TermekSzolgaltatasTetelekTipus }
     * 
     * 
     */
    public List<TermekSzolgaltatasTetelekTipus> getTermekSzolgaltatasTetelek() {
        if (termekSzolgaltatasTetelek == null) {
            termekSzolgaltatasTetelek = new ArrayList<TermekSzolgaltatasTetelekTipus>();
        }
        return this.termekSzolgaltatasTetelek;
    }

    /**
     * Gets the value of the modositoSzla property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modositoSzla property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModositoSzla().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModositoSzlaTipus }
     * 
     * 
     */
    public List<ModositoSzlaTipus> getModositoSzla() {
        if (modositoSzla == null) {
            modositoSzla = new ArrayList<ModositoSzlaTipus>();
        }
        return this.modositoSzla;
    }

    /**
     * Gets the value of the gyujtoSzla property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gyujtoSzla property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGyujtoSzla().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GyujtoSzlaTipus }
     * 
     * 
     */
    public List<GyujtoSzlaTipus> getGyujtoSzla() {
        if (gyujtoSzla == null) {
            gyujtoSzla = new ArrayList<GyujtoSzlaTipus>();
        }
        return this.gyujtoSzla;
    }

    /**
     * Gets the value of the zaradekok property.
     * 
     * @return
     *     possible object is
     *     {@link ZaradekokTipus }
     *     
     */
    public ZaradekokTipus getZaradekok() {
        return zaradekok;
    }

    /**
     * Sets the value of the zaradekok property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZaradekokTipus }
     *     
     */
    public void setZaradekok(ZaradekokTipus value) {
        this.zaradekok = value;
    }

    /**
     * Gets the value of the nemKotelezo property.
     * 
     * @return
     *     possible object is
     *     {@link NemKotelezoTipus }
     *     
     */
    public NemKotelezoTipus getNemKotelezo() {
        return nemKotelezo;
    }

    /**
     * Sets the value of the nemKotelezo property.
     * 
     * @param value
     *     allowed object is
     *     {@link NemKotelezoTipus }
     *     
     */
    public void setNemKotelezo(NemKotelezoTipus value) {
        this.nemKotelezo = value;
    }

    /**
     * Gets the value of the osszesites property.
     * 
     * @return
     *     possible object is
     *     {@link OsszesitesTipus }
     *     
     */
    public OsszesitesTipus getOsszesites() {
        return osszesites;
    }

    /**
     * Sets the value of the osszesites property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsszesitesTipus }
     *     
     */
    public void setOsszesites(OsszesitesTipus value) {
        this.osszesites = value;
    }

    public void setTermekSzolgaltatasTetelek(List<TermekSzolgaltatasTetelekTipus> termekSzolgaltatasTetelek) {
        this.termekSzolgaltatasTetelek = termekSzolgaltatasTetelek;
    }
    

}
