//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:11:04 PM CET 
//


package cezeszamlazo.hu.gov.nav.schemas._2013.szamla;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for szamlakibocsato_tipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="szamlakibocsato_tipus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adoszam" type="{http://schemas.nav.gov.hu/2013/szamla}adoszam_tipus"/>
 *         &lt;element name="kozadoszam" type="{http://schemas.nav.gov.hu/2013/szamla}adoszam_tipus" minOccurs="0"/>
 *         &lt;element name="kisadozo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="nev" type="{http://schemas.nav.gov.hu/2013/szamla}string_tipus"/>
 *         &lt;element name="cim" type="{http://schemas.nav.gov.hu/2013/szamla}cim_tipus"/>
 *         &lt;element name="egyeni_vallalkozo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ev_nyilv_tart_szam" type="{http://schemas.nav.gov.hu/2013/szamla}string_tipus" minOccurs="0"/>
 *         &lt;element name="ev_neve" type="{http://schemas.nav.gov.hu/2013/szamla}string_tipus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "szamlakibocsato_tipus", propOrder = {
    "adoszam",
    "kozadoszam",
    "kisadozo",
    "nev",
    "cim",
    "egyeniVallalkozo",
    "evNyilvTartSzam",
    "evNeve"
})
public class SzamlakibocsatoTipus {

    @XmlElement(required = true)
    protected String adoszam;
    protected String kozadoszam;
    protected Boolean kisadozo;
    @XmlElement(required = true)
    protected String nev;
    @XmlElement(required = true)
    protected CimTipus cim;
    @XmlElement(name = "egyeni_vallalkozo")
    protected Boolean egyeniVallalkozo;
    @XmlElement(name = "ev_nyilv_tart_szam")
    protected String evNyilvTartSzam;
    @XmlElement(name = "ev_neve")
    protected String evNeve;

    /**
     * Gets the value of the adoszam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdoszam() {
        return adoszam;
    }

    /**
     * Sets the value of the adoszam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdoszam(String value) {
        this.adoszam = value;
    }

    /**
     * Gets the value of the kozadoszam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKozadoszam() {
        return kozadoszam;
    }

    /**
     * Sets the value of the kozadoszam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKozadoszam(String value) {
        this.kozadoszam = value;
    }

    /**
     * Gets the value of the kisadozo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKisadozo() {
        return kisadozo;
    }

    /**
     * Sets the value of the kisadozo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKisadozo(Boolean value) {
        this.kisadozo = value;
    }

    /**
     * Gets the value of the nev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNev() {
        return nev;
    }

    /**
     * Sets the value of the nev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNev(String value) {
        this.nev = value;
    }

    /**
     * Gets the value of the cim property.
     * 
     * @return
     *     possible object is
     *     {@link CimTipus }
     *     
     */
    public CimTipus getCim() {
        return cim;
    }

    /**
     * Sets the value of the cim property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimTipus }
     *     
     */
    public void setCim(CimTipus value) {
        this.cim = value;
    }

    /**
     * Gets the value of the egyeniVallalkozo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEgyeniVallalkozo() {
        return egyeniVallalkozo;
    }

    /**
     * Sets the value of the egyeniVallalkozo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEgyeniVallalkozo(Boolean value) {
        this.egyeniVallalkozo = value;
    }

    /**
     * Gets the value of the evNyilvTartSzam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvNyilvTartSzam() {
        return evNyilvTartSzam;
    }

    /**
     * Sets the value of the evNyilvTartSzam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvNyilvTartSzam(String value) {
        this.evNyilvTartSzam = value;
    }

    /**
     * Gets the value of the evNeve property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvNeve() {
        return evNeve;
    }

    /**
     * Sets the value of the evNeve property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvNeve(String value) {
        this.evNeve = value;
    }

}
