//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:11:04 PM CET 
//


package cezeszamlazo.hu.gov.nav.schemas._2013.szamla;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vegosszeg_tipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vegosszeg_tipus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nettoarossz" type="{http://schemas.nav.gov.hu/2013/szamla}decimal_tipus" minOccurs="0"/>
 *         &lt;element name="afaertekossz" type="{http://schemas.nav.gov.hu/2013/szamla}decimal_tipus" minOccurs="0"/>
 *         &lt;element name="bruttoarossz" type="{http://schemas.nav.gov.hu/2013/szamla}decimal_tipus" minOccurs="0"/>
 *         &lt;element name="afa_tartalom" type="{http://schemas.nav.gov.hu/2013/szamla}decimal_tipus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vegosszeg_tipus", propOrder = {
    "nettoarossz",
    "afaertekossz",
    "bruttoarossz",
    "afaTartalom"
})
public class VegosszegTipus {

    protected BigDecimal nettoarossz;
    protected BigDecimal afaertekossz;
    protected BigDecimal bruttoarossz;
    @XmlElement(name = "afa_tartalom")
    protected BigDecimal afaTartalom;

    /**
     * Gets the value of the nettoarossz property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNettoarossz() {
        return nettoarossz;
    }

    /**
     * Sets the value of the nettoarossz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNettoarossz(BigDecimal value) {
        this.nettoarossz = value;
    }

    /**
     * Gets the value of the afaertekossz property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAfaertekossz() {
        return afaertekossz;
    }

    /**
     * Sets the value of the afaertekossz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAfaertekossz(BigDecimal value) {
        this.afaertekossz = value;
    }

    /**
     * Gets the value of the bruttoarossz property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBruttoarossz() {
        return bruttoarossz;
    }

    /**
     * Sets the value of the bruttoarossz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBruttoarossz(BigDecimal value) {
        this.bruttoarossz = value;
    }

    /**
     * Gets the value of the afaTartalom property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAfaTartalom() {
        return afaTartalom;
    }

    /**
     * Sets the value of the afaTartalom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAfaTartalom(BigDecimal value) {
        this.afaTartalom = value;
    }

}
