//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:11:04 PM CET 
//


package cezeszamlazo.hu.gov.nav.schemas._2013.szamla;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for vissz_igeny_tipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vissz_igeny_tipus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vissz_igenytetel" type="{http://schemas.nav.gov.hu/2013/szamla}vissz_igenytetel_tipus" maxOccurs="unbounded"/>
 *         &lt;element name="szla" type="{http://schemas.nav.gov.hu/2013/szamla}string_tipus"/>
 *         &lt;element name="szla_kelte" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="kotelezett_neve" type="{http://schemas.nav.gov.hu/2013/szamla}string_tipus"/>
 *         &lt;element name="kotelezett_cime" type="{http://schemas.nav.gov.hu/2013/szamla}cim_tipus"/>
 *         &lt;element name="kotelezett_adoszama" type="{http://schemas.nav.gov.hu/2013/szamla}adoszam_tipus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vissz_igeny_tipus", propOrder = {
    "visszIgenytetel",
    "szla",
    "szlaKelte",
    "kotelezettNeve",
    "kotelezettCime",
    "kotelezettAdoszama"
})
public class VisszIgenyTipus {

    @XmlElement(name = "vissz_igenytetel", required = true)
    protected List<VisszIgenytetelTipus> visszIgenytetel;
    @XmlElement(required = true)
    protected String szla;
    @XmlElement(name = "szla_kelte", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar szlaKelte;
    @XmlElement(name = "kotelezett_neve", required = true)
    protected String kotelezettNeve;
    @XmlElement(name = "kotelezett_cime", required = true)
    protected CimTipus kotelezettCime;
    @XmlElement(name = "kotelezett_adoszama", required = true)
    protected String kotelezettAdoszama;

    /**
     * Gets the value of the visszIgenytetel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visszIgenytetel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisszIgenytetel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VisszIgenytetelTipus }
     * 
     * 
     */
    public List<VisszIgenytetelTipus> getVisszIgenytetel() {
        if (visszIgenytetel == null) {
            visszIgenytetel = new ArrayList<VisszIgenytetelTipus>();
        }
        return this.visszIgenytetel;
    }

    /**
     * Gets the value of the szla property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSzla() {
        return szla;
    }

    /**
     * Sets the value of the szla property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSzla(String value) {
        this.szla = value;
    }

    /**
     * Gets the value of the szlaKelte property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSzlaKelte() {
        return szlaKelte;
    }

    /**
     * Sets the value of the szlaKelte property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSzlaKelte(XMLGregorianCalendar value) {
        this.szlaKelte = value;
    }

    /**
     * Gets the value of the kotelezettNeve property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKotelezettNeve() {
        return kotelezettNeve;
    }

    /**
     * Sets the value of the kotelezettNeve property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKotelezettNeve(String value) {
        this.kotelezettNeve = value;
    }

    /**
     * Gets the value of the kotelezettCime property.
     * 
     * @return
     *     possible object is
     *     {@link CimTipus }
     *     
     */
    public CimTipus getKotelezettCime() {
        return kotelezettCime;
    }

    /**
     * Sets the value of the kotelezettCime property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimTipus }
     *     
     */
    public void setKotelezettCime(CimTipus value) {
        this.kotelezettCime = value;
    }

    /**
     * Gets the value of the kotelezettAdoszama property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKotelezettAdoszama() {
        return kotelezettAdoszama;
    }

    /**
     * Sets the value of the kotelezettAdoszama property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKotelezettAdoszama(String value) {
        this.kotelezettAdoszama = value;
    }

}
