package view;

import java.awt.Dimension;
import java.awt.FontMetrics;
import java.awt.Toolkit;

/**
 * @author Tomy
 */
public class UserMessage extends javax.swing.JDialog
{
    private String messageTitle;
    private String description;
    
    public UserMessage(String messageTitle, String description)
    {
        initComponents();
        
        this.messageTitle = messageTitle;
        this.description = description;
        
        Init();
    }
    
    private void Init()
    {
        SetTitle();
        SetDescription();
        
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;
        
        setLocation(x, y);
        setModal(true);
        setVisible(true);
    }
    
    private void SetTitle()
    {
        label_MessageTitle.setText(messageTitle);
    }
    
    private void SetDescription()
    {
        textArea_Description.setText(description);
        
        FontMetrics metrics = textArea_Description.getFontMetrics(textArea_Description.getFont());

        String [] rows = description.split("\n");
        int maxWidth = 0;
        
        for(int i = 0; i < rows.length; i++)
        {
            int rowWidth = metrics.stringWidth(rows[i]);
            
            if(rowWidth > maxWidth)
            {
                maxWidth = rowWidth;
            }
        }
        
        int lineWidth = maxWidth;
        int lineHeight = metrics.getHeight() * rows.length + 4;
        
        Dimension size = new Dimension(lineWidth + 40, lineHeight);
        
        this.setSize(new Dimension(lineWidth + 40, 105 + lineHeight));
        
        panel_Description.setPreferredSize(size);
        
        textArea_Description.setPreferredSize(size);
    }
    
    private void Close()
    {
        setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_MessageTitle = new javax.swing.JLabel();
        panel_Description = new javax.swing.JPanel();
        textArea_Description = new javax.swing.JTextArea();
        button_OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(126, 90));

        label_MessageTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_MessageTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_MessageTitle.setText("Short message");

        textArea_Description.setBackground(new java.awt.Color(240, 240, 240));
        textArea_Description.setColumns(20);
        textArea_Description.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textArea_Description.setRows(5);
        textArea_Description.setText("Long description");
        textArea_Description.setEnabled(false);

        javax.swing.GroupLayout panel_DescriptionLayout = new javax.swing.GroupLayout(panel_Description);
        panel_Description.setLayout(panel_DescriptionLayout);
        panel_DescriptionLayout.setHorizontalGroup(
            panel_DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textArea_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panel_DescriptionLayout.setVerticalGroup(
            panel_DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DescriptionLayout.createSequentialGroup()
                .addComponent(textArea_Description, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        button_OK.setText("Ok");
        button_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_MessageTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_Description, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(button_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_MessageTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_OK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_OKActionPerformed
        Close();
    }//GEN-LAST:event_button_OKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_OK;
    private javax.swing.JLabel label_MessageTitle;
    private javax.swing.JPanel panel_Description;
    private javax.swing.JTextArea textArea_Description;
    // End of variables declaration//GEN-END:variables

    //SETTERS
    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    //GETTERS
    public String getMessageTitle() {
        return messageTitle;
    }

    public String getDescription() {
        return description;
    }
}