package cezeszamlazo.views;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JTextField;

/**
 * @author adam.papp, Tomy
 */
public class EmptyFieldChangeView extends javax.swing.JDialog
{
    public static final int RET_CANCEL = 0;
    public static final int RET_OK = 1;
    
    private JTextField field;
    private String changeString;
    private int returnStatus = RET_CANCEL;
    
    public EmptyFieldChangeView(String message, String changeString, String change, String back, JTextField field)
    {
        this.field = field;
        this.changeString = changeString;
        
        initComponents();
        
        Init(message, changeString, change, back);
    }
    
    private void Init(String message, String changeString, String change, String back)
    {
        setMessage(message, changeString, change, back);
        
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;
        
        java.net.URL url = ClassLoader.getSystemResource("cezeszamlazo/resources/error.png");
	java.awt.Image img = toolkit.createImage(url);
	setIconImage(img);

	setLocation(x, y);

	BackgroundThread b = new BackgroundThread();
        b.start();

	setModal(true);
	setVisible(true);
    }
    
    private void setMessage(String message, String changeString, String change, String back)
    {
        String s = message + changeString;
        String [] split = s.split("/n");
        
        label_FirstLine.setText(split[0]);
        
        if(split.length == 2)
        {
            label_SecondLine.setText(split[1]);
        }
        else
        {
            label_SecondLine.setText("");
        }
        
        if (change.isEmpty())
        {
	    button_ApplyChanges.setVisible(false);
	}
        else
        {
	    button_ApplyChanges.setToolTipText(change);
	}

	if (back.isEmpty())
        {
	    button_ExitEmptyFieldChangeView.setVisible(false);
	}
        else
        {
	    button_ExitEmptyFieldChangeView.setToolTipText(back);
	}
    }
    
    private void Close(int status)
    {
        returnStatus = status;
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_dialog = new javax.swing.JPanel();
        label_ErrorIcon = new javax.swing.JLabel();
        label_FirstLine = new javax.swing.JLabel();
        label_SecondLine = new javax.swing.JLabel();
        button_ApplyChanges = new javax.swing.JButton();
        button_ExitEmptyFieldChangeView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        panel_dialog.setName("panel_dialog"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cezeszamlazo.App.class).getContext().getResourceMap(EmptyFieldChangeView.class);
        label_ErrorIcon.setIcon(resourceMap.getIcon("label_ErrorIcon.icon")); // NOI18N
        label_ErrorIcon.setText(resourceMap.getString("label_ErrorIcon.text")); // NOI18N
        label_ErrorIcon.setName("label_ErrorIcon"); // NOI18N

        label_FirstLine.setFont(resourceMap.getFont("label_FirstLine.font")); // NOI18N
        label_FirstLine.setText(resourceMap.getString("label_FirstLine.text")); // NOI18N
        label_FirstLine.setName("label_FirstLine"); // NOI18N

        label_SecondLine.setFont(resourceMap.getFont("label_SecondLine.font")); // NOI18N
        label_SecondLine.setText(resourceMap.getString("label_SecondLine.text")); // NOI18N
        label_SecondLine.setName("label_SecondLine"); // NOI18N

        button_ApplyChanges.setIcon(resourceMap.getIcon("button_ApplyChanges.icon")); // NOI18N
        button_ApplyChanges.setText(resourceMap.getString("button_ApplyChanges.text")); // NOI18N
        button_ApplyChanges.setName("button_ApplyChanges"); // NOI18N
        button_ApplyChanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_ApplyChangesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_ApplyChangesMouseExited(evt);
            }
        });
        button_ApplyChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ApplyChangesActionPerformed(evt);
            }
        });

        button_ExitEmptyFieldChangeView.setIcon(resourceMap.getIcon("button_ExitEmptyFieldChangeView.icon")); // NOI18N
        button_ExitEmptyFieldChangeView.setText(resourceMap.getString("button_ExitEmptyFieldChangeView.text")); // NOI18N
        button_ExitEmptyFieldChangeView.setName("button_ExitEmptyFieldChangeView"); // NOI18N
        button_ExitEmptyFieldChangeView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_ExitEmptyFieldChangeViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_ExitEmptyFieldChangeViewMouseExited(evt);
            }
        });
        button_ExitEmptyFieldChangeView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ExitEmptyFieldChangeViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_dialogLayout = new javax.swing.GroupLayout(panel_dialog);
        panel_dialog.setLayout(panel_dialogLayout);
        panel_dialogLayout.setHorizontalGroup(
            panel_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_ErrorIcon)
                .addGap(18, 18, 18)
                .addGroup(panel_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_FirstLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_SecondLine, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_ApplyChanges)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_ExitEmptyFieldChangeView)
                .addContainerGap())
        );
        panel_dialogLayout.setVerticalGroup(
            panel_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_ErrorIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_dialogLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(panel_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_ExitEmptyFieldChangeView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_dialogLayout.createSequentialGroup()
                                .addComponent(label_FirstLine)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_SecondLine, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                                .addGap(7, 7, 7))
                            .addGroup(panel_dialogLayout.createSequentialGroup()
                                .addComponent(button_ApplyChanges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_dialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_dialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_ApplyChangesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ApplyChangesMouseEntered
        button_ApplyChanges.setBackground(Color.decode("#abd043"));
    }//GEN-LAST:event_button_ApplyChangesMouseEntered

    private void button_ApplyChangesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ApplyChangesMouseExited
        button_ApplyChanges.setBackground(Color.decode("#f0f0f0"));
    }//GEN-LAST:event_button_ApplyChangesMouseExited

    private void button_ApplyChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ApplyChangesActionPerformed
        field.setText(changeString);
        
        Close(RET_OK);
    }//GEN-LAST:event_button_ApplyChangesActionPerformed

    private void button_ExitEmptyFieldChangeViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ExitEmptyFieldChangeViewMouseEntered
        button_ExitEmptyFieldChangeView.setBackground(Color.decode("#d24343"));
    }//GEN-LAST:event_button_ExitEmptyFieldChangeViewMouseEntered

    private void button_ExitEmptyFieldChangeViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ExitEmptyFieldChangeViewMouseExited
        button_ExitEmptyFieldChangeView.setBackground(Color.decode("#f0f0f0"));
    }//GEN-LAST:event_button_ExitEmptyFieldChangeViewMouseExited

    private void button_ExitEmptyFieldChangeViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ExitEmptyFieldChangeViewActionPerformed
        Close(RET_CANCEL);
    }//GEN-LAST:event_button_ExitEmptyFieldChangeViewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ApplyChanges;
    private javax.swing.JButton button_ExitEmptyFieldChangeView;
    private javax.swing.JLabel label_ErrorIcon;
    private javax.swing.JLabel label_FirstLine;
    private javax.swing.JLabel label_SecondLine;
    private javax.swing.JPanel panel_dialog;
    // End of variables declaration//GEN-END:variables

    class BackgroundThread extends Thread
    {
        public BackgroundThread()
        {
            
        }
        
        public void run()
        {
            for (int j = 0; j < 2; j++)
            {
		for (int i = 240; i < 255; i++)
                {
		    String c = "#"
                        + Integer.toHexString(0x100 | i).substring(1).toUpperCase()
                        + Integer.toHexString(0x100 | i).substring(1).toUpperCase()
                        + Integer.toHexString(0x100 | i).substring(1).toUpperCase();
		    panel_dialog.setBackground(Color.decode(c));
		    try
                    {
			Thread.sleep(5);
		    }
                    catch (Exception e){}
		}
		for (int i = 255; i >= 240; i--)
                {
		    String c = "#"
                        + Integer.toHexString(0x100 | i).substring(1).toUpperCase()
                        + Integer.toHexString(0x100 | i).substring(1).toUpperCase()
                        + Integer.toHexString(0x100 | i).substring(1).toUpperCase();
		    panel_dialog.setBackground(Color.decode(c));
		    try
                    {
			Thread.sleep(5);
		    } catch (Exception e){}
		}
	    }
        }
    }

    public int getReturnStatus()
    {
        return returnStatus;
    }
}