/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cezeszamlazo;

import cezeszamlazo.CalendarDialog;
import cezeszamlazo.HibaDialog;
import cezeszamlazo.SzamlaDialogOld;
import cezeszamlazo.hu.gov.nav.schemas._2013.szamla.GenerateXml;
import cezeszamlazo.hu.gov.nav.schemas._2013.szamla.GenerateXml;
import java.awt.Dimension;
import java.awt.Point;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author GRAFIKA2
 */
public class AdatszolgaltatasFrame extends javax.swing.JFrame {

    protected GenerateXml genarateXml;

    /**
     * Creates new form AdatszolgaltatasFrame
     */
    public AdatszolgaltatasFrame() {
        initComponents();
        init();
        genarateXml = new GenerateXml();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kezdoDatum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        zaroDatum = new javax.swing.JTextField();
        datumRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        PPRadioButton = new javax.swing.JRadioButton();
        CZTextFieldYearBegin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        MSTextFieldStart = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        MSTextFieldYearEnd = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        MSTextFieldEnd = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PPTextFieldYearBegin = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        PPTextFieldStart = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        CZTextFieldStart = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PPTextFieldYearEnd = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CZTextFieldYearEnd = new javax.swing.JTextField();
        PPTextFieldEnd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        CZTextFieldEnd = new javax.swing.JTextField();
        CZRadioButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        MSRadioButton = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        MSTextFieldYearBegin = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cezeszamlazo.App.class).getContext().getResourceMap(AdatszolgaltatasFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        kezdoDatum.setEditable(false);
        kezdoDatum.setBackground(resourceMap.getColor("kezdoDatum.background")); // NOI18N
        kezdoDatum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kezdoDatum.setDisabledTextColor(resourceMap.getColor("kezdoDatum.disabledTextColor")); // NOI18N
        kezdoDatum.setEnabled(false);
        kezdoDatum.setName("kezdoDatum"); // NOI18N
        kezdoDatum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kezdoDatumMouseClicked(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        zaroDatum.setEditable(false);
        zaroDatum.setBackground(resourceMap.getColor("zaroDatum.background")); // NOI18N
        zaroDatum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        zaroDatum.setDisabledTextColor(resourceMap.getColor("zaroDatum.disabledTextColor")); // NOI18N
        zaroDatum.setEnabled(false);
        zaroDatum.setName("zaroDatum"); // NOI18N
        zaroDatum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zaroDatumMouseClicked(evt);
            }
        });

        datumRadioButton.setText(resourceMap.getString("datumRadioButton.text")); // NOI18N
        datumRadioButton.setName("datumRadioButton"); // NOI18N
        datumRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datumRadioButtonActionPerformed(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        PPRadioButton.setText(resourceMap.getString("PPRadioButton.text")); // NOI18N
        PPRadioButton.setName("PPRadioButton"); // NOI18N
        PPRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPRadioButtonActionPerformed(evt);
            }
        });

        CZTextFieldYearBegin.setText(resourceMap.getString("CZTextFieldYearBegin.text")); // NOI18N
        CZTextFieldYearBegin.setName("CZTextFieldYearBegin"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        MSTextFieldStart.setName("MSTextFieldStart"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        MSTextFieldYearEnd.setText(resourceMap.getString("MSTextFieldYearEnd.text")); // NOI18N
        MSTextFieldYearEnd.setName("MSTextFieldYearEnd"); // NOI18N

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        MSTextFieldEnd.setName("MSTextFieldEnd"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        PPTextFieldYearBegin.setText(resourceMap.getString("PPTextFieldYearBegin.text")); // NOI18N
        PPTextFieldYearBegin.setName("PPTextFieldYearBegin"); // NOI18N

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        PPTextFieldStart.setName("PPTextFieldStart"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel23.setIcon(resourceMap.getIcon("jLabel23.icon")); // NOI18N
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.setName("jLabel23"); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        CZTextFieldStart.setText(resourceMap.getString("CZTextFieldStart.text")); // NOI18N
        CZTextFieldStart.setName("CZTextFieldStart"); // NOI18N

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        PPTextFieldYearEnd.setText(resourceMap.getString("PPTextFieldYearEnd.text")); // NOI18N
        PPTextFieldYearEnd.setName("PPTextFieldYearEnd"); // NOI18N

        jLabel24.setIcon(resourceMap.getIcon("jLabel24.icon")); // NOI18N
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.setName("jLabel24"); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        CZTextFieldYearEnd.setText(resourceMap.getString("CZTextFieldYearEnd.text")); // NOI18N
        CZTextFieldYearEnd.setName("CZTextFieldYearEnd"); // NOI18N

        PPTextFieldEnd.setName("PPTextFieldEnd"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        CZTextFieldEnd.setText(resourceMap.getString("CZTextFieldEnd.text")); // NOI18N
        CZTextFieldEnd.setName("CZTextFieldEnd"); // NOI18N

        CZRadioButton.setText(resourceMap.getString("CZRadioButton.text")); // NOI18N
        CZRadioButton.setName("CZRadioButton"); // NOI18N
        CZRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CZRadioButtonActionPerformed(evt);
            }
        });

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        MSRadioButton.setText(resourceMap.getString("MSRadioButton.text")); // NOI18N
        MSRadioButton.setName("MSRadioButton"); // NOI18N
        MSRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSRadioButtonActionPerformed(evt);
            }
        });

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        MSTextFieldYearBegin.setText(resourceMap.getString("MSTextFieldYearBegin.text")); // NOI18N
        MSTextFieldYearBegin.setName("MSTextFieldYearBegin"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MSRadioButton)
                    .addComponent(PPRadioButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(2, 2, 2)
                                .addComponent(MSTextFieldYearBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MSTextFieldStart, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MSTextFieldYearEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MSTextFieldEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(2, 2, 2)
                                .addComponent(PPTextFieldYearBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PPTextFieldStart, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PPTextFieldYearEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PPTextFieldEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datumRadioButton)
                            .addComponent(CZRadioButton))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CZTextFieldYearBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CZTextFieldStart, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CZTextFieldYearEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CZTextFieldEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kezdoDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zaroDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(zaroDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(kezdoDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(datumRadioButton))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(CZTextFieldYearBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(CZTextFieldStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(CZRadioButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(CZTextFieldYearEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(CZTextFieldEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MSRadioButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(MSTextFieldYearBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(MSTextFieldStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(MSTextFieldEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MSTextFieldYearEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19)
                        .addComponent(PPTextFieldYearBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PPTextFieldStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(PPTextFieldYearEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(PPTextFieldEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22))
                    .addComponent(PPRadioButton))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datumRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datumRadioButtonActionPerformed
        CZRadioButton.setSelected(false);
        MSRadioButton.setSelected(false);
        PPRadioButton.setSelected(false);
    }//GEN-LAST:event_datumRadioButtonActionPerformed

    private void CZRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CZRadioButtonActionPerformed
        datumRadioButton.setSelected(false);
        MSRadioButton.setSelected(false);
        PPRadioButton.setSelected(false);
    }//GEN-LAST:event_CZRadioButtonActionPerformed

    private void MSRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSRadioButtonActionPerformed
        datumRadioButton.setSelected(false);
        CZRadioButton.setSelected(false);
        PPRadioButton.setSelected(false);
    }//GEN-LAST:event_MSRadioButtonActionPerformed

    private void PPRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPRadioButtonActionPerformed
        datumRadioButton.setSelected(false);
        CZRadioButton.setSelected(false);
        MSRadioButton.setSelected(false);
    }//GEN-LAST:event_PPRadioButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean OK = true;
        if (datumRadioButton.isSelected()) {
            if (kezdoDatum.getText().equals("")) {
                HibaDialog h = new HibaDialog("A kezdő dátum nem lehet üres!", "Ok", "");
                OK = false;
            } else if (zaroDatum.getText().equals("")) {
                HibaDialog h = new HibaDialog("A záró dátum nem lehet üres!", "Ok", "");
                OK = false;
            }

        } else if (CZRadioButton.isSelected()) {
            if (CZTextFieldYearBegin.getText().equals("")) {
                HibaDialog h = new HibaDialog("A kezdő év nem lehet üres!", "Ok", "");
                OK = false;
            } else if (CZTextFieldYearEnd.getText().equals("")) {
                HibaDialog h = new HibaDialog("A záró év nem lehet üres!", "Ok", "");
                OK = false;
            } else if (CZTextFieldStart.getText().equals("")) {
                HibaDialog h = new HibaDialog("A kezdő szám nem lehet üres!", "Ok", "");
                OK = false;
            } else if (CZTextFieldEnd.getText().equals("")) {
                HibaDialog h = new HibaDialog("A záró szám nem lehet üres!", "Ok", "");
                OK = false;
            }
        } else if (MSRadioButton.isSelected()) {
            if (MSTextFieldYearBegin.getText().equals("")) {
                HibaDialog h = new HibaDialog("A kezdő év nem lehet üres!", "Ok", "");
                OK = false;
            } else if (MSTextFieldYearEnd.getText().equals("")) {
                HibaDialog h = new HibaDialog("A záró év nem lehet üres!", "Ok", "");
                OK = false;
            } else if (MSTextFieldStart.getText().equals("")) {
                HibaDialog h = new HibaDialog("A kezdő szám nem lehet üres!", "Ok", "");
                OK = false;
            } else if (MSTextFieldEnd.getText().equals("")) {
                HibaDialog h = new HibaDialog("A záró szám nem lehet üres!", "Ok", "");
                OK = false;
            }
        } else if (PPRadioButton.isSelected()) {
            if (PPTextFieldYearBegin.getText().equals("")) {
                HibaDialog h = new HibaDialog("A kezdő év nem lehet üres!", "Ok", "");
                OK = false;
            } else if (PPTextFieldYearEnd.getText().equals("")) {
                HibaDialog h = new HibaDialog("A záró év nem lehet üres!", "Ok", "");
                OK = false;
            } else if (PPTextFieldStart.getText().equals("")) {
                HibaDialog h = new HibaDialog("A kezdő szám nem lehet üres!", "Ok", "");
                OK = false;
            } else if (PPTextFieldEnd.getText().equals("")) {
                HibaDialog h = new HibaDialog("A záró szám nem lehet üres!", "Ok", "");
                OK = false;
            }
        }
        if (OK) {

            File file = new File("szamlak.xml");
            try {
                JFileChooser chooser = new JFileChooser();
                chooser.setSelectedFile(file);
                chooser.showOpenDialog(null);
                File curFile = chooser.getSelectedFile();
                if (curFile != null) {
                    String type = "";
                    int yearBegin = 0;
                    int yearEnd = 0;
                    int start = 0;
                    int end = 0;

                    if (datumRadioButton.isSelected()) {
                        if (kezdoDatum.getText().equals("")) {
                            HibaDialog h = new HibaDialog("A kezdő dátum nem lehet üres!", "Ok", "");
                        } else if (zaroDatum.getText().equals("")) {
                            HibaDialog h = new HibaDialog("A záró dátum nem lehet üres!", "Ok", "");
                        } else {
                            genarateXml.generateByDate(kezdoDatum.getText(), zaroDatum.getText(), curFile);
                        }

                    } else {
                        if (CZRadioButton.isSelected()) {
                            type = "CZ";
                            yearBegin = Integer.parseInt(CZTextFieldYearBegin.getText());
                            yearEnd = Integer.parseInt(CZTextFieldYearEnd.getText());
                            start = Integer.parseInt(CZTextFieldStart.getText());
                            end = Integer.parseInt(CZTextFieldEnd.getText());

                        } else if (MSRadioButton.isSelected()) {
                            type = "MS";
                            yearBegin = Integer.parseInt(MSTextFieldYearBegin.getText());
                            yearEnd = Integer.parseInt(MSTextFieldYearEnd.getText());
                            start = Integer.parseInt(MSTextFieldStart.getText());
                            end = Integer.parseInt(MSTextFieldEnd.getText());
                        } else if (PPRadioButton.isSelected()) {
                            type = "PP";
                            yearBegin = Integer.parseInt(PPTextFieldYearBegin.getText());
                            yearEnd = Integer.parseInt(PPTextFieldYearEnd.getText());
                            start = Integer.parseInt(PPTextFieldStart.getText());
                            end = Integer.parseInt(PPTextFieldEnd.getText());
                        }

                        genarateXml.generateBySorszam(type, yearBegin, yearEnd, start, end, file);
                    }

                }
            } catch (Exception ex) {
                ex.printStackTrace();
                HibaDialog h = new HibaDialog("Ebben az intervallumban nincsenek számlák! ", "Ok", "");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void kezdoDatumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kezdoDatumMouseClicked
        CalendarDialog cd = new CalendarDialog(null, kezdoDatum);
    }//GEN-LAST:event_kezdoDatumMouseClicked

    private void zaroDatumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zaroDatumMouseClicked
        CalendarDialog cd = new CalendarDialog(null, zaroDatum);
    }//GEN-LAST:event_zaroDatumMouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        CalendarDialog cd = new CalendarDialog(null, zaroDatum);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        CalendarDialog cd = new CalendarDialog(null, kezdoDatum);
    }//GEN-LAST:event_jLabel24MouseClicked

    public void nyit() {
        setVisible(true);
    }

    private void nyit(Object dialog, String title) {
        if (dialog instanceof JDialog) {
            JDialog d = (JDialog) dialog;
            Dimension appSize = getSize();
            Point appLocation = getLocation();
            int x = (appSize.width - d.getWidth()) / 2 + appLocation.x;
            int y = (appSize.height - d.getHeight()) / 2 + appLocation.y;
            d.setLocation(x, y);
            d.setTitle(title);
            d.setVisible(true);
        } else if (dialog instanceof JFrame) {
            JFrame f = (JFrame) dialog;
            Dimension appSize = getSize();
            Point appLocation = getLocation();
            int x = (appSize.width - f.getWidth()) / 2 + appLocation.x;
            int y = (appSize.height - f.getHeight()) / 2 + appLocation.y;
            f.setLocation(x, y);
            f.setTitle(title);
            f.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CZRadioButton;
    private javax.swing.JTextField CZTextFieldEnd;
    private javax.swing.JTextField CZTextFieldStart;
    private javax.swing.JTextField CZTextFieldYearBegin;
    private javax.swing.JTextField CZTextFieldYearEnd;
    private javax.swing.JRadioButton MSRadioButton;
    private javax.swing.JTextField MSTextFieldEnd;
    private javax.swing.JTextField MSTextFieldStart;
    private javax.swing.JTextField MSTextFieldYearBegin;
    private javax.swing.JTextField MSTextFieldYearEnd;
    private javax.swing.JRadioButton PPRadioButton;
    private javax.swing.JTextField PPTextFieldEnd;
    private javax.swing.JTextField PPTextFieldStart;
    private javax.swing.JTextField PPTextFieldYearBegin;
    private javax.swing.JTextField PPTextFieldYearEnd;
    private javax.swing.JRadioButton datumRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kezdoDatum;
    private javax.swing.JTextField zaroDatum;
    // End of variables declaration//GEN-END:variables

    private void init() {
        datumRadioButton.setSelected(true);
//        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cezeszamlazo.App.class).getContext().getResourceMap(SzamlaDialogOld.class);
//        jLabel24.setIcon(resourceMap.getIcon("calendar_16.png")); // NOI18N
//        jLabel23.setIcon(resourceMap.getIcon("calendar_16.png")); // NOI18N
    }
}
