/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SzallitoAdatokDialog.java
 *
 * Created on 2014.08.21., 9:37:10
 */
package cezeszamlazo;

import cezeszamlazo.controller.Szallito;
import cezeszamlazo.database.Query;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author pappadam
 */
public class SzallitoAdatokDialog extends javax.swing.JDialog {

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    private Szallito szallito;

    /** Creates new form SzallitoAdatokDialog */
    public SzallitoAdatokDialog(Szallito szallito) {
        initComponents();

        this.szallito = szallito;

        init();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {

            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        szallitoNev = new javax.swing.JTextField();
        jLabel106 = new javax.swing.JLabel();
        szallitoVaros = new javax.swing.JTextField();
        szallitoUtca = new javax.swing.JTextField();
        szallitoIrsz = new javax.swing.JTextField();
        jLabel101 = new javax.swing.JLabel();
        szallitoBankszamlaszam = new javax.swing.JTextField();
        jLabel103 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        szallitoAdoszam = new javax.swing.JTextField();
        szallitoMegjegyzes = new javax.swing.JTextField();
        jLabel102 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jButton1.setName("jButton1"); // NOI18N

        szallitoNev.setName("szallitoNev"); // NOI18N
        szallitoNev.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                szallitoNevFocusLost(evt);
            }
        });

        jLabel106.setName("jLabel106"); // NOI18N

        szallitoVaros.setName("szallitoVaros"); // NOI18N
        szallitoVaros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                szallitoVarosFocusLost(evt);
            }
        });

        szallitoUtca.setName("szallitoUtca"); // NOI18N
        szallitoUtca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                szallitoUtcaFocusLost(evt);
            }
        });

        szallitoIrsz.setName("szallitoIrsz"); // NOI18N
        szallitoIrsz.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                szallitoIrszFocusLost(evt);
            }
        });
        szallitoIrsz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                szallitoIrszKeyReleased(evt);
            }
        });

        jLabel101.setName("jLabel101"); // NOI18N

        szallitoBankszamlaszam.setName("szallitoBankszamlaszam"); // NOI18N
        szallitoBankszamlaszam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                szallitoBankszamlaszamFocusLost(evt);
            }
        });

        jLabel103.setName("jLabel103"); // NOI18N

        jLabel111.setName("jLabel111"); // NOI18N

        jLabel104.setName("jLabel104"); // NOI18N

        szallitoAdoszam.setName("szallitoAdoszam"); // NOI18N
        szallitoAdoszam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                szallitoAdoszamFocusLost(evt);
            }
        });

        szallitoMegjegyzes.setName("szallitoMegjegyzes"); // NOI18N
        szallitoMegjegyzes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                szallitoMegjegyzesFocusLost(evt);
            }
        });

        jLabel102.setName("jLabel102"); // NOI18N

        jLabel105.setName("jLabel105"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel104, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(szallitoUtca, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(szallitoIrsz, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel106)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(szallitoVaros, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                            .addComponent(szallitoNev, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(szallitoAdoszam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel105, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(szallitoBankszamlaszam, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(szallitoMegjegyzes, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel101)
                    .addComponent(szallitoNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel102)
                    .addComponent(szallitoIrsz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel106)
                    .addComponent(szallitoVaros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel103)
                    .addComponent(szallitoUtca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel104)
                    .addComponent(szallitoAdoszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel105)
                    .addComponent(szallitoBankszamlaszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel111)
                    .addComponent(szallitoMegjegyzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

private void szallitoIrszKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_szallitoIrszKeyReleased
    if (szallitoIrsz.getText().length() == 4) {
        Query query = new Query.QueryBuilder()
                .select("CONCAT(varos, IF(v = 1, CONCAT('-', varosresz), ''))")
                .from("varosok")
                .where("irsz = '" + szallitoIrsz.getText() + "'")
                .build();
        Object[][] s = App.db.select(query.getQuery());
        if (s.length == 1) {
            szallito.setVaros(String.valueOf(s[0][0]));
            szallitoVaros.setText(szallito.getVaros());
        }
    }
}//GEN-LAST:event_szallitoIrszKeyReleased

private void szallitoNevFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_szallitoNevFocusLost
    szallito.setNev(szallitoNev.getText());
}//GEN-LAST:event_szallitoNevFocusLost

private void szallitoIrszFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_szallitoIrszFocusLost
    szallito.setIrsz(szallitoIrsz.getText());
}//GEN-LAST:event_szallitoIrszFocusLost

private void szallitoVarosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_szallitoVarosFocusLost
    szallito.setVaros(szallitoVaros.getText());
}//GEN-LAST:event_szallitoVarosFocusLost

private void szallitoUtcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_szallitoUtcaFocusLost
    szallito.setUtca(szallitoUtca.getText());
}//GEN-LAST:event_szallitoUtcaFocusLost

private void szallitoAdoszamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_szallitoAdoszamFocusLost
    szallito.setAdoszam(szallitoAdoszam.getText());
}//GEN-LAST:event_szallitoAdoszamFocusLost

private void szallitoBankszamlaszamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_szallitoBankszamlaszamFocusLost
    szallito.setBankszamlaszam(szallitoBankszamlaszam.getText());
}//GEN-LAST:event_szallitoBankszamlaszamFocusLost

private void szallitoMegjegyzesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_szallitoMegjegyzesFocusLost
    szallito.setMegjegyzes(szallitoMegjegyzes.getText());
}//GEN-LAST:event_szallitoMegjegyzesFocusLost

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JTextField szallitoAdoszam;
    private javax.swing.JTextField szallitoBankszamlaszam;
    private javax.swing.JTextField szallitoIrsz;
    private javax.swing.JTextField szallitoMegjegyzes;
    private javax.swing.JTextField szallitoNev;
    private javax.swing.JTextField szallitoUtca;
    private javax.swing.JTextField szallitoVaros;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;

    private void init() {
        szallitoNev.setText(szallito.getNev());
        szallitoIrsz.setText(szallito.getIrsz());
        szallitoVaros.setText(szallito.getVaros());
        szallitoUtca.setText(szallito.getAddress());
        szallitoAdoszam.setText(szallito.getAdoszam());
        szallitoBankszamlaszam.setText(szallito.getBankszamlaszam());
        szallitoMegjegyzes.setText(szallito.getMegjegyzes());

        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;

        java.net.URL url = ClassLoader.getSystemResource("cezeszamlazo/resources/icon.png");
        java.awt.Image img = toolkit.createImage(url);

        setIconImage(img);

        setLocation(x, y);
        setTitle("Szállító adatok");
        setModal(true);
        setVisible(true);
    }

    public Szallito getSzallito() {
        return szallito;
    }
}
