package cezeszamlazo;

import cezeszamlazo.database.Query;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

public class UjCsoportDialog extends javax.swing.JDialog
{
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    private String id = "0";
    private boolean isSzamlaCsoport = true;

    public UjCsoportDialog(String id, boolean isSzamlaCsoport)
    {
        initComponents();

        this.id = id;
        this.isSzamlaCsoport = isSzamlaCsoport;

        Object[][] select;

        String title = "";
        
        if (isSzamlaCsoport && id.equalsIgnoreCase("0"))
        {
            title = "Új számla csoport";
        }
        else if (isSzamlaCsoport && !id.equalsIgnoreCase("0"))
        {
            title = "Számla csoport módosítás";
            
            Query query = new Query.QueryBuilder()
                .select("nev, leiras")
                .from("szamlazo_szamla_csoportok")
                .where("id = " + id)
                .build();
            select = App.db.select(query.getQuery());
            
            nev.setText(String.valueOf(select[0][0]));
            leiras.setText(String.valueOf(select[0][1]));
        }
        else if (!isSzamlaCsoport && id.equalsIgnoreCase("0"))
        {
            title = "Új termék csoport";
        }
        else if (!isSzamlaCsoport && !id.equalsIgnoreCase("0"))
        {
            title = "Termék csoport módosítás";
            
            Query query = new Query.QueryBuilder()
                .select("nev, leiras ")
                .from("szamlazo_termek_csoportok")
                .where("id = " + id)
                .build();
            select = App.db.select(query.getQuery());
            
            nev.setText(String.valueOf(select[0][0]));
            leiras.setText(String.valueOf(select[0][1]));
        }
        
        init(title);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {

            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leiras = new javax.swing.JTextArea();
        nev = new javax.swing.JTextField();

        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cezeszamlazo.App.class).getContext().getResourceMap(UjCsoportDialog.class);
        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        leiras.setColumns(20);
        leiras.setFont(resourceMap.getFont("leiras.font")); // NOI18N
        leiras.setRows(5);
        leiras.setName("leiras"); // NOI18N
        jScrollPane1.setViewportView(leiras);

        nev.setText(resourceMap.getString("nev.text")); // NOI18N
        nev.setName("nev"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nev, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (nev.getText().isEmpty())
        {
            HibaDialog h = new HibaDialog("Nincs megadva név!", "Ok", "");
        } else
        {
            Object[] o = new Object[2];
            o[0] = nev.getText();
            o[1] = leiras.getText();
            
            if (isSzamlaCsoport && id.equalsIgnoreCase("0")) {
                App.db.insert("INSERT INTO szamlazo_szamla_csoportok (nev, leiras) VALUES (?, ?)", o);
            } else if (isSzamlaCsoport && !id.equalsIgnoreCase("0")) {
                App.db.insert("UPDATE szamlazo_szamla_csoportok SET nev = ?, leiras = ? WHERE id = " + id, o);
            } else if (!isSzamlaCsoport && id.equalsIgnoreCase("0")) {
                App.db.insert("INSERT INTO szamlazo_termek_csoportok (nev, leiras) VALUES (?, ?)", o);
            } else if (!isSzamlaCsoport && !id.equalsIgnoreCase("0")) {
                App.db.insert("UPDATE szamlazo_termek_csoportok SET nev = ?, leiras = ? WHERE id = " + id, o);
            }
            
            doClose(RET_OK);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void doClose(int retStatus)
    {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea leiras;
    private javax.swing.JTextField nev;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;

    private void init(String title)
    {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;

        java.net.URL url;
        
        if (isSzamlaCsoport)
        {
            url = ClassLoader.getSystemResource("cezeszamlazo/resources/uj-szamla-csoportok-16.png");
        }
        else
        {
            url = ClassLoader.getSystemResource("cezeszamlazo/resources/uj-termek-csoportok-16.png");
        }
        
        java.awt.Image img = toolkit.createImage(url);

        setIconImage(img);
        setLocation(x, y);
        setTitle(title);

        setModal(true);
        setVisible(true);
    }
}