/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cezeszamlazo.ugyfel;

import cezeszamlazo.HibaDialog;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Fejlesztés
 */
public class UgyfelCsoportositasDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    /**
     * 
     */
    private Ugyfel[] ugyfelek;
    
    private int actual = 0;

    /**
     * Creates new form UjUgyfelDialog
     */
    public UgyfelCsoportositasDialog(int[] ids) {
        initComponents();
        
        this.ugyfelek = Ugyfel.getUgyfelekArray(ids);

        init();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bankszamlaszamText = new javax.swing.JTextField();
        adoszamText = new javax.swing.JTextField();
        utcaText = new javax.swing.JTextField();
        irszText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        varosText = new javax.swing.JTextField();
        nevText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kedvezmenySpinner = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        prevButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        countLabel = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        okButton.setText("Csoportosítás");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancelButton.setText("Mégse");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Név:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Irsz:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Utca, hsz.:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Adószám:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Bankszámlaszám:");

        bankszamlaszamText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bankszamlaszamText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankszamlaszamTextActionPerformed(evt);
            }
        });
        bankszamlaszamText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankszamlaszamTextFocusLost(evt);
            }
        });

        adoszamText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        adoszamText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoszamTextActionPerformed(evt);
            }
        });
        adoszamText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                adoszamTextFocusLost(evt);
            }
        });

        utcaText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        utcaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utcaTextActionPerformed(evt);
            }
        });
        utcaText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                utcaTextFocusLost(evt);
            }
        });

        irszText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        irszText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irszTextActionPerformed(evt);
            }
        });
        irszText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                irszTextFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Város:");

        varosText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        varosText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varosTextActionPerformed(evt);
            }
        });
        varosText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varosTextFocusLost(evt);
            }
        });

        nevText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nevText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nevTextActionPerformed(evt);
            }
        });
        nevText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nevTextFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Kedvezmény:");

        kedvezmenySpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kedvezmenySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                kedvezmenySpinnerStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("% az optimális árból");

        prevButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prevButton.setText("<");
        prevButton.setMargin(new java.awt.Insets(6, 12, 6, 12));
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        nextButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nextButton.setText(">");
        nextButton.setMargin(new java.awt.Insets(6, 12, 6, 12));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        countLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        countLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countLabel.setText("1/10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankszamlaszamText)
                            .addComponent(adoszamText)
                            .addComponent(utcaText)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(irszText, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varosText, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                            .addComponent(nevText)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kedvezmenySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prevButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(countLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prevButton)
                        .addComponent(nextButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nevText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(irszText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(varosText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(utcaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(adoszamText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bankszamlaszamText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kedvezmenySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okButton)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        mentes();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void nevTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nevTextFocusLost
        ugyfelek[actual].setNev(nevText.getText());
    }//GEN-LAST:event_nevTextFocusLost

    private void irszTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_irszTextFocusLost
        ugyfelek[actual].setIrsz(irszText.getText());
    }//GEN-LAST:event_irszTextFocusLost

    private void varosTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varosTextFocusLost
        ugyfelek[actual].setVaros(varosText.getText());
    }//GEN-LAST:event_varosTextFocusLost

    private void utcaTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_utcaTextFocusLost
        ugyfelek[actual].setUtca(utcaText.getText());
    }//GEN-LAST:event_utcaTextFocusLost

    private void adoszamTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adoszamTextFocusLost
        ugyfelek[actual].setAdoszam(adoszamText.getText());
    }//GEN-LAST:event_adoszamTextFocusLost

    private void bankszamlaszamTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bankszamlaszamTextFocusLost
        ugyfelek[actual].setBankszamlaszam(bankszamlaszamText.getText());
    }//GEN-LAST:event_bankszamlaszamTextFocusLost

    private void nevTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nevTextActionPerformed
        ugyfelek[actual].setNev(nevText.getText());
        mentes();
    }//GEN-LAST:event_nevTextActionPerformed

    private void irszTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irszTextActionPerformed
        ugyfelek[actual].setIrsz(irszText.getText());
        mentes();
    }//GEN-LAST:event_irszTextActionPerformed

    private void varosTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varosTextActionPerformed
        ugyfelek[actual].setVaros(varosText.getText());
        mentes();
    }//GEN-LAST:event_varosTextActionPerformed

    private void utcaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utcaTextActionPerformed
        ugyfelek[actual].setUtca(utcaText.getText());
        mentes();
    }//GEN-LAST:event_utcaTextActionPerformed

    private void adoszamTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoszamTextActionPerformed
        ugyfelek[actual].setAdoszam(adoszamText.getText());
        mentes();
    }//GEN-LAST:event_adoszamTextActionPerformed

    private void bankszamlaszamTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankszamlaszamTextActionPerformed
        ugyfelek[actual].setBankszamlaszam(bankszamlaszamText.getText());
        mentes();
    }//GEN-LAST:event_bankszamlaszamTextActionPerformed

    private void kedvezmenySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_kedvezmenySpinnerStateChanged
        ugyfelek[actual].setKedvezmeny(Integer.parseInt(String.valueOf(kedvezmenySpinner.getValue())));
    }//GEN-LAST:event_kedvezmenySpinnerStateChanged

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        actual--;
        if (actual < 0) {
            actual = ugyfelek.length - 1;
        }
        kitolt();
    }//GEN-LAST:event_prevButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        actual++;
        if (actual > ugyfelek.length - 1) {
            actual = 0;
        }
        kitolt();
    }//GEN-LAST:event_nextButtonActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adoszamText;
    private javax.swing.JTextField bankszamlaszamText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel countLabel;
    private javax.swing.JTextField irszText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner kedvezmenySpinner;
    private javax.swing.JTextField nevText;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton okButton;
    private javax.swing.JButton prevButton;
    private javax.swing.JTextField utcaText;
    private javax.swing.JTextField varosText;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
    
    private void init() {
                
        kitolt();

        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;

        setModal(true);
//        setIconImage(PixiRendszer.img);
        setLocation(x, y);
        setTitle("Ügyfél csoportos egyesítés");
        setVisible(true);
    }
    
    private void kitolt() {
        countLabel.setText((actual + 1) + "/" + ugyfelek.length);
        
        nevText.setText(ugyfelek[actual].getNev());
        irszText.setText(ugyfelek[actual].getIrsz());
        varosText.setText(ugyfelek[actual].getVaros());
        utcaText.setText(ugyfelek[actual].getUtca());
        adoszamText.setText(ugyfelek[actual].getAdoszam());
        bankszamlaszamText.setText(ugyfelek[actual].getBankszamlaszam());
        kedvezmenySpinner.setValue(ugyfelek[actual].getKedvezmeny());
    }
    
    private void mentes() {
        String s = ugyfelek[actual].valid();
        if (s.isEmpty()) {
            ugyfelek[actual].mentes();
            Ugyfel.csoportositas(ugyfelek, ugyfelek[actual]);
            doClose(RET_OK);
        } else {
            HibaDialog h = new HibaDialog(s, "", "Ok");
        }
    }
    
    public int getId() {
        return ugyfelek[actual].getId();
    }
    
}
