/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cezeszamlazo.ugyfel;

import cezeszamlazo.App;
import cezeszamlazo.HibaDialog;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Fejlesztés
 */
public class UgyfelekFrame extends javax.swing.JFrame
{
    /**
     * Creates new form UgyfelekFrame
     */
    public UgyfelekFrame()
    {
        initComponents();

        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        openMenuItem = new javax.swing.JMenuItem();
        csoportositasMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        deleteMenuItem = new javax.swing.JMenuItem();
        keresesText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        toggleSelected = new javax.swing.JButton();

        openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cezeszamlazo/resources/images/open_16.png"))); // NOI18N
        openMenuItem.setText("Megnyitás/módosítás");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        popupMenu.add(openMenuItem);

        csoportositasMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cezeszamlazo/resources/images/osszevonas_16.png"))); // NOI18N
        csoportositasMenuItem.setText("Kijelöltek csoportosítása");
        csoportositasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csoportositasMenuItemActionPerformed(evt);
            }
        });
        popupMenu.add(csoportositasMenuItem);
        popupMenu.add(jSeparator1);

        deleteMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cezeszamlazo/resources/images/delete_16.png"))); // NOI18N
        deleteMenuItem.setText("Törlés");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        popupMenu.add(deleteMenuItem);

        keresesText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        keresesText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keresesTextKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Új ügyfél");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(25);
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        toggleSelected.setText("Kiválasztottak");
        toggleSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(keresesText, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toggleSelected)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keresesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(toggleSelected))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keresesTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keresesTextKeyReleased
        frissites();
    }//GEN-LAST:event_keresesTextKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UjUgyfelDialog uud = new UjUgyfelDialog();
        
        if (uud.getReturnStatus() == UjUgyfelDialog.RET_OK)
        {
            frissites();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void toggleSelectedActionPerformed(java.awt.event.ActionEvent evt)
    {
        if (kijeloltUgyfelekFrame == null)
        {
            kijeloltUgyfelekFrame = new KijeloltUgyfelekFrame<>((int) (this.getLocation().getX() + this.getSize().getWidth()), (int) (this.getLocation().getY()), this);
            kijeloltUgyfelekFrame.fillUp(produceData());
        }

        if (kijeloltUgyfelekFrame.isVisible())
        {
            kijeloltUgyfelekFrame.setVisible(false);
        }
        else
        {
            kijeloltUgyfelekFrame.sortTable(generateRegex());
            kijeloltUgyfelekFrame.nyit();
        }
    }

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int row = table.getSelectedRow();
        
        if (row >= 0 && evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() == 2)
        {
            megnyitas(row);
        }
    }//GEN-LAST:event_tableMouseClicked

    private Map<Integer, String> produceData()
    {
        Map<Integer, String> data = new HashMap<>();

        for (int i = 0; i < table.getRowCount(); i++)
        {
            data.put(Integer.parseInt(String.valueOf(table.getValueAt(i, 0))), String.valueOf(table.getValueAt(i, 1)));
        }
//    	for(int i = 0; i<table.getRowCount(); i++){
//    		if ((boolean) table.getValueAt(i, 5)){
//    			data.put(Integer.parseInt(String.valueOf(table.getValueAt(i, 0))),String.valueOf(table.getValueAt(i, 1)));
//    		}
//    	}

        return data;
    }

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        int row = table.getSelectedRow();
        if (row >= 0) {
            megnyitas(row);
        }
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        HibaDialog h = new HibaDialog("Biztosan törlöd az ügyfelet?", "Igen", "Nem");
        
        if (h.getReturnStatus() == HibaDialog.RET_OK)
        {
            int row = table.getSelectedRow();
            Ugyfel ugyfel = new Ugyfel(Integer.parseInt(String.valueOf(table.getValueAt(row, 0))));
            ugyfel.torles();
            frissites();
        }
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
        if (evt.isPopupTrigger()) {
            JTable source = (JTable) evt.getSource();
            int row = source.rowAtPoint(evt.getPoint());
            int column = source.columnAtPoint(evt.getPoint());

            if (!source.isRowSelected(row)) {
                source.changeSelection(row, column, false, false);
            }

            boolean tobbSor = (source.getSelectedRows().length > 1);

            openMenuItem.setEnabled(!tobbSor);
            deleteMenuItem.setEnabled(!tobbSor);

            csoportositasMenuItem.setEnabled(tobbSor);

            popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }


    }//GEN-LAST:event_tableMouseReleased

    private String generateRegex()
    {
        String regex = "";

        regex += "^(";
//    	for(int i=0; i<selected.length; i++){
//    		regex += String.valueOf(table.getValueAt(selected[i], 0)) + "|";
//    	}

        for (int i = 0; i < table.getRowCount(); i++) {
            if ((boolean) table.getValueAt(i, 5)) {
                regex += String.valueOf(table.getValueAt(i, 0)) + "|";
            }
        }

        regex = regex.substring(0, regex.length() - 1);
        regex += ")$";

        if (regex.equals("^)$")) {
            return "^(Nothing matches to this pattern)$";
        }

        return regex;
    }

    private void csoportositasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csoportositasMenuItemActionPerformed
        int[] rows = table.getSelectedRows();
        int[] ids = new int[rows.length];
        
        for (int i = 0; i < rows.length; i++)
        {
            ids[i] = Integer.parseInt(String.valueOf(table.getValueAt(rows[i], 0)));
        }
        
        UgyfelCsoportositasDialog ucsd = new UgyfelCsoportositasDialog(ids);
        
        if (ucsd.getReturnStatus() == UgyfelCsoportositasDialog.RET_OK)
        {
            frissites();
        }
    }//GEN-LAST:event_csoportositasMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem csoportositasMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField keresesText;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JTable table;
    private javax.swing.JButton toggleSelected;
    // End of variables declaration//GEN-END:variables

//    private javax.swing.JButton toggleSelected;
    private KijeloltUgyfelekFrame<UgyfelekFrame> kijeloltUgyfelekFrame;

    public void init()
    {
//      deleteMenuItem.setVisible(PixiRendszer.user.getJogosultsag() != 0);
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;

//      setIconImage(PixiRendszer.img);
        setLocation(x, y);
        setTitle("Ügyfelek");
    }

    public void frissites()
    {
        String w = "1";
        String k = keresesText.getText();
        if (!k.isEmpty()) {
            w += " && (name LIKE '%" + k + "%' || postalCode LIKE '%" + k + "%' || city LIKE '%" + k + "%' || street LIKE'%" + k + "%' || publicPlace LIKE'%" + k + "%' || houseNumber LIKE'%" + k + "%' || taxNumber LIKE '%" + k + "%' || bankAccountNumber LIKE '%" + k + "%')";
        }
//        if (PixiRendszer.user.getJogosultsag() == PixiUser.USER) {
//            w += " && userid = " + PixiRendszer.user.getId();
//        }
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        String[] header = {"Id", "Név", "Cím", "Adószám", "Bankszámlaszám", "Kiválasztott"};
//        model.setDataVector(PixiRendszer.db.select("SELECT id, nev, CONCAT(irsz, ' ', varos, ', ', utca), adoszam, bankszamlaszam "
//                + "FROM pixi_ugyfel "
//                + "WHERE  " + w + " "
//                + "ORDER BY nev ASC"), header);

        //TODO szebben
        Object[][] vector1 = App.db.select("SELECT id, name, CONCAT(postalCode, ' ', city, ', ', street, ' ', publicPlace, ' ', houseNumber), taxNumber, bankAccountNumber "
                + "FROM szamlazo_customers "
                + "WHERE  " + w + " "
                + "ORDER BY name ASC");

        Object[][] vector2 = new Object[0][0];
        
        if (vector1.length > 0)
        {
            vector2 = new Object[vector1.length][vector1[0].length + 1];
        }

        for (int i = 0; i < vector1.length; i++)
        {
            for (int j = 0; j < vector1[0].length; j++)
            {
                vector2[i][j] = vector1[i][j];
            }
            vector2[i][vector1[0].length] = false;
        }

        model.setDataVector(vector2, header);

        DefaultTableRender render = new DefaultTableRender();
        TableColumn col;
        int[] meret = {30, 150, 100, 50, 100};
        
        for (int i = 0; i < meret.length; i++)
        {
            col = table.getColumnModel().getColumn(i);
            col.setPreferredWidth(meret[i]);
            col.setCellRenderer(render);
        }
        
        if (kijeloltUgyfelekFrame != null)
        {
            kijeloltUgyfelekFrame.fillUp(produceData());
            kijeloltUgyfelekFrame.sortTable(generateRegex());
        }
    }

    private void megnyitas(int row)
    {
        UjUgyfelDialog uud = new UjUgyfelDialog(Integer.parseInt(String.valueOf(table.getValueAt(row, 0))));
        
        if (uud.getReturnStatus() == UjUgyfelDialog.RET_OK)
        {
            frissites();
        }
    }

    public void setSelected(ArrayList<Integer> ids)
    {
        table.clearSelection();
        for (int i = 0; i < table.getRowCount(); i++)
        {
            if (ids.contains(Integer.valueOf(String.valueOf(table.getValueAt(i, 0)))))
            {
//    		if (ids.contains(table.getValueAt(i, 0))){
                table.addRowSelectionInterval(i, i);
            }
        }
    }

    public void nyit()
    {
        frissites();
        setVisible(true);
    }
}