/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cezeszamlazo.ugyfel;

import cezeszamlazo.App;
import cezeszamlazo.HibaDialog;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Fejlesztés
 */
public class UjKapcsolattartoDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    /**
     * segédváltozó combo boxhoz
     */
    private boolean b = true;

    /**
     *
     */
    private Kapcsolattarto kapcsolattarto;

    public UjKapcsolattartoDialog(int id) {
        initComponents();

        String title = "";

        if (id == 0) {
            title = "Új kapcsolattartó";
            kapcsolattarto = new Kapcsolattarto();
        } else {
            title = "Kapcsolattartó módosítása";
            kapcsolattarto = new Kapcsolattarto(id);
        }
        init(title);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    public UjKapcsolattartoDialog() {
        this(0);
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        telefonText = new javax.swing.JTextField();
        nevText = new javax.swing.JTextField();
        ugyfelComboBox = new javax.swing.JComboBox();
        ujUgyfelButton = new javax.swing.JButton();
        emailText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hirlevelCheckBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        penzugyesCheckBox = new javax.swing.JCheckBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        okButton.setText("Mentés");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancelButton.setText("Mégse");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Ügyfél:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Név:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Telefon:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Email:");

        telefonText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        telefonText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonTextActionPerformed(evt);
            }
        });
        telefonText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonTextFocusLost(evt);
            }
        });

        nevText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nevText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nevTextActionPerformed(evt);
            }
        });
        nevText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nevTextFocusLost(evt);
            }
        });

        ugyfelComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ugyfelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ügyfelek" }));
        ugyfelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugyfelComboBoxActionPerformed(evt);
            }
        });

        ujUgyfelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ujUgyfelButton.setText("Új ügyfél");
        ujUgyfelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ujUgyfelButtonActionPerformed(evt);
            }
        });

        emailText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });
        emailText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Hírlevél:");

        hirlevelCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hirlevelCheckBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Pénzügyes:");

        penzugyesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penzugyesCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ugyfelComboBox, 0, 226, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ujUgyfelButton))
                            .addComponent(nevText)
                            .addComponent(telefonText)
                            .addComponent(emailText)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(hirlevelCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(penzugyesCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ugyfelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ujUgyfelButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nevText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(telefonText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hirlevelCheckBox))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(penzugyesCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addGap(24, 24, 24))
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        mentes();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void nevTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nevTextFocusLost
        kapcsolattarto.setNev(nevText.getText());
    }//GEN-LAST:event_nevTextFocusLost

    private void telefonTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonTextFocusLost
        kapcsolattarto.setTelefon(telefonText.getText());
    }//GEN-LAST:event_telefonTextFocusLost

    private void emailTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFocusLost
        kapcsolattarto.setEmail(emailText.getText());
    }//GEN-LAST:event_emailTextFocusLost

    private void ujUgyfelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ujUgyfelButtonActionPerformed
        UjUgyfelDialog uud = new UjUgyfelDialog();
        if (uud.getReturnStatus() == UjKapcsolattartoDialog.RET_OK) {
            ugyfelComboBoxFrissites(uud.getId());
        }
    }//GEN-LAST:event_ujUgyfelButtonActionPerformed

    private void ugyfelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugyfelComboBoxActionPerformed
        if (b) {
            Label l = (Label) ugyfelComboBox.getSelectedItem();
            kapcsolattarto.setUgyfelId((int) l.getId());
        }
    }//GEN-LAST:event_ugyfelComboBoxActionPerformed

    private void nevTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nevTextActionPerformed
        kapcsolattarto.setNev(nevText.getText());
        mentes();
    }//GEN-LAST:event_nevTextActionPerformed

    private void telefonTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonTextActionPerformed
        kapcsolattarto.setTelefon(telefonText.getText());
        mentes();
    }//GEN-LAST:event_telefonTextActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        kapcsolattarto.setEmail(emailText.getText());
        mentes();
    }//GEN-LAST:event_emailTextActionPerformed

    private void hirlevelCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hirlevelCheckBoxActionPerformed
        kapcsolattarto.setHirlevel(hirlevelCheckBox.isSelected());
    }//GEN-LAST:event_hirlevelCheckBoxActionPerformed

    private void penzugyesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penzugyesCheckBoxActionPerformed
        kapcsolattarto.setPenzugyes(penzugyesCheckBox.isSelected());
    }//GEN-LAST:event_penzugyesCheckBoxActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField emailText;
    private javax.swing.JCheckBox hirlevelCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nevText;
    private javax.swing.JButton okButton;
    private javax.swing.JCheckBox penzugyesCheckBox;
    private javax.swing.JTextField telefonText;
    private javax.swing.JComboBox ugyfelComboBox;
    private javax.swing.JButton ujUgyfelButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;

    private void init(String title) {

        ugyfelComboBoxFrissites(kapcsolattarto.getUgyfelId());
        nevText.setText(kapcsolattarto.getNev());
        telefonText.setText(kapcsolattarto.getTelefon());
        emailText.setText(kapcsolattarto.getEmail());
        hirlevelCheckBox.setSelected(kapcsolattarto.isHirlevel());
        penzugyesCheckBox.setSelected(kapcsolattarto.isPenzugyes());

        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;

        setModal(true);
//        setIconImage(PixiRendszer.img);
        setLocation(x, y);
        setTitle(title);
        setVisible(true);
    }

    private void ugyfelComboBoxFrissites(int id) {
        b = false;
        ugyfelComboBox.removeAllItems();
        ugyfelComboBox.addItem(new Label(0, "minden ügyfél"));
        String w = "1";
//        if (PixiRendszer.user.getJogosultsag() == PixiUser.USER) {
        w = "userid = " + App.user.getId();
//        }
        Object[][] s = null;
        if (w.equalsIgnoreCase("1")) {
//            System.out.println("w: " + w);
            s = App.db.select("SELECT id, nev FROM pixi_ugyfel WHERE 1 ORDER BY nev ASC");
        } else {
            s = App.db.select("SELECT id, nev FROM pixi_ugyfel WHERE " + w + " ORDER BY nev ASC");
        }

        int index = 0;
        for (int i = 0; i < s.length; i++) {
            int uid = Integer.parseInt(String.valueOf(s[i][0]));
            ugyfelComboBox.addItem(new Label(uid, String.valueOf(s[i][1])));
            if (uid == id) {
                index = i + 1;
            }
        }
        b = true;
        ugyfelComboBox.setSelectedIndex(index);
    }

    private void mentes() {
        String s = kapcsolattarto.valid();
        if (s.isEmpty()) {
            kapcsolattarto.mentes();
            doClose(RET_OK);
        } else {
            HibaDialog h = new HibaDialog(s, "", "Ok");
        }
    }

    public int getId() {
        return kapcsolattarto.getId();
    }
}
